services:
  fastapi:
    image: dwani/discovery-server:latest  # Replace with your FastAPI Docker image
    container_name: fastapi_server
    ports:
      - "8000:18888"  # Expose FastAPI server port (adjust if needed)
    environment:
      - DWANI_API_BASE_URL=https://
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to host's localhost
    restart: unless-stopped
  # Development server (hot reload)
  discovery-ux:
    image: dwani/discovery-ux-dev:latest  # Replace with your FastAPI Docker image
    container_name: discovery-ux
    ports:
      - "5173:5173"       # Vite dev server default port
      - "3000:3000"       # Optional: if you use another port
    environment:
      - VITE_DWANI_API_KEY=asdasd  # Pass your API key
      - VITE_DWANI_API_BASE_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge